executed: '2024-11-18T14:24:22.191Z'
results:
  - code: openapi-external-docs-error
    message: OpenAPI MUST Have External Documentation
    path: []
    severity: 0
    range:
      start:
        line: 0
        character: 0
      end:
        line: 122
        character: 44
  - code: openapi-tags-object-error
    message: OpenAPIs MUST Have a Tag Object
    path: []
    severity: 0
    range:
      start:
        line: 0
        character: 0
      end:
        line: 122
        character: 44
  - code: openapi-info-contact-error
    message: Info MUST Have Contact Object
    path:
      - info
    severity: 0
    range:
      start:
        line: 1
        character: 5
      end:
        line: 6
        character: 16
  - code: openapi-info-license-error
    message: Info MUST Have License
    path:
      - info
    severity: 0
    range:
      start:
        line: 1
        character: 5
      end:
        line: 6
        character: 16
  - code: openapi-info-terms-of-service-error
    message: Info MUST Have Terms of Service
    path:
      - info
    severity: 0
    range:
      start:
        line: 1
        character: 5
      end:
        line: 6
        character: 16
  - code: openapi-info-title-info
    message: Info Has Title
    path:
      - info
      - title
    severity: 2
    range:
      start:
        line: 2
        character: 9
      end:
        line: 2
        character: 19
  - code: openapi-info-title-upper-case-info
    message: Info Title MUST Have First Characters Capitalized
    path:
      - info
      - title
    severity: 2
    range:
      start:
        line: 2
        character: 9
      end:
        line: 2
        character: 19
  - code: openapi-info-description-info
    message: Info Has Description
    path:
      - info
      - description
    severity: 2
    range:
      start:
        line: 3
        character: 15
      end:
        line: 5
        character: 19
  - code: openapi-info-version-info
    message: Info Has Version
    path:
      - info
      - version
    severity: 2
    range:
      start:
        line: 6
        character: 11
      end:
        line: 6
        character: 16
  - code: openapi-no-api-in-path-error
    message: No API in Path
    path:
      - paths
      - /v1/config
    severity: 0
    range:
      start:
        line: 8
        character: 13
      end:
        line: 122
        character: 44
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
    path:
      - paths
      - /v1/config
    severity: 2
    range:
      start:
        line: 8
        character: 13
      end:
        line: 122
        character: 44
  - code: openapi-version-in-path-error
    message: Version in Path
    path:
      - paths
      - /v1/config
    severity: 0
    range:
      start:
        line: 8
        character: 13
      end:
        line: 122
        character: 44
  - code: openapi-no-request-body-on-get-info
    message: GET Request Body
    path:
      - paths
      - /v1/config
      - get
    severity: 2
    range:
      start:
        line: 9
        character: 8
      end:
        line: 122
        character: 44
  - code: openapi-operation-security-definitions-error
    message: Operations MUST Have a Security Definition
    path:
      - paths
      - /v1/config
      - get
    severity: 0
    range:
      start:
        line: 9
        character: 8
      end:
        line: 122
        character: 44
  - code: openapi-operations-operation-ids-error
    message: Operation MUST Have Identifier
    path:
      - paths
      - /v1/config
      - get
    severity: 0
    range:
      start:
        line: 9
        character: 8
      end:
        line: 122
        character: 44
  - code: openapi-operations-tags-error
    message: Operations MUST Have Tags
    path:
      - paths
      - /v1/config
      - get
    severity: 0
    range:
      start:
        line: 9
        character: 8
      end:
        line: 122
        character: 44
  - code: openapi-operations-summary-info
    message: Operation Has a Summary
    path:
      - paths
      - /v1/config
      - get
      - summary
    severity: 2
    range:
      start:
        line: 10
        character: 15
      end:
        line: 10
        character: 36
  - code: openapi-operations-summary-period-none-info
    message: Operation Has a Period.
    path:
      - paths
      - /v1/config
      - get
      - summary
    severity: 2
    range:
      start:
        line: 10
        character: 15
      end:
        line: 10
        character: 36
  - code: openapi-operations-description-info
    message: Operation Has Description
    path:
      - paths
      - /v1/config
      - get
      - description
    severity: 2
    range:
      start:
        line: 11
        character: 19
      end:
        line: 13
        character: 34
  - code: openapi-parameters-componentized-error
    message: Parameters MUST use components $ref.
    path:
      - paths
      - /v1/config
      - get
      - parameters
      - '0'
    severity: 0
    range:
      start:
        line: 15
        character: 10
      end:
        line: 20
        character: 25
  - code: openapi-response-get-400-status-code-error
    message: GET Responses MUST Have 400 Status Codes
    path:
      - paths
      - /v1/config
      - get
      - responses
    severity: 0
    range:
      start:
        line: 21
        character: 16
      end:
        line: 99
        character: 47
  - code: openapi-response-get-401-status-code-error
    message: GET Responses Has 401 Status Code
    path:
      - paths
      - /v1/config
      - get
      - responses
    severity: 0
    range:
      start:
        line: 21
        character: 16
      end:
        line: 99
        character: 47
  - code: openapi-response-get-403-status-code-error
    message: GET Responses Has 403 Status Code
    path:
      - paths
      - /v1/config
      - get
      - responses
    severity: 0
    range:
      start:
        line: 21
        character: 16
      end:
        line: 99
        character: 47
  - code: openapi-response-get-429-status-code-error
    message: GET Responses Has 429 Status Code
    path:
      - paths
      - /v1/config
      - get
      - responses
    severity: 0
    range:
      start:
        line: 21
        character: 16
      end:
        line: 99
        character: 47
  - code: openapi-response-get-200-status-code-info
    message: GET Responses Has 200 Status Codes
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
    severity: 2
    range:
      start:
        line: 22
        character: 14
      end:
        line: 89
        character: 59
  - code: openapi-response-get-200-description-info
    message: GET 200 Response has description.
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - description
    severity: 2
    range:
      start:
        line: 23
        character: 23
      end:
        line: 23
        character: 60
  - code: openapi-response-get-200-content-info
    message: GET 200 Response Has Content.
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - content
    severity: 2
    range:
      start:
        line: 24
        character: 18
      end:
        line: 89
        character: 59
  - code: openapi-response-get-200-media-type-examples-error
    message: GET 200 Response MUST Have Examples
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 0
    range:
      start:
        line: 25
        character: 29
      end:
        line: 89
        character: 59
  - code: openapi-response-get-200-media-type-info
    message: GET 200 Response Has Media Type.
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - content
      - application/json
    severity: 2
    range:
      start:
        line: 25
        character: 29
      end:
        line: 89
        character: 59
  - code: openapi-response-get-200-media-type-schema-info
    message: GET 200 Response Has Schema
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - content
      - application/json
      - schema
    severity: 2
    range:
      start:
        line: 26
        character: 21
      end:
        line: 89
        character: 59
  - code: openapi-response-get-200-media-type-schema-ref-info
    message: GET 200 Responses Uses Schema Reference
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '200'
      - content
      - application/json
      - schema
    severity: 2
    range:
      start:
        line: 26
        character: 21
      end:
        line: 89
        character: 59
  - code: openapi-response-get-500-schema-ref-info
    message: GET 500 Responses Uses Schema Reference
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '500'
    severity: 2
    range:
      start:
        line: 90
        character: 14
      end:
        line: 99
        character: 47
  - code: openapi-response-get-500-status-code-info
    message: GET Responses Has 500 Status Code
    path:
      - paths
      - /v1/config
      - get
      - responses
      - '500'
    severity: 2
    range:
      start:
        line: 90
        character: 14
      end:
        line: 99
        character: 47
